# Redis connection
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

---
# Production Redis repository options
spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      repositories:
        enabled: false
